var car = 'subaru';
console.log(car == 'subaru');
var bike = 'honda';
console.log(bike == 'honda');
var fridge = 'dawlance';
console.log(fridge == 'haier');
var book = 'rich dad poor dad';
console.log(book == 'the fastlane millionarie');
var fish = 'Shark';
console.log(fish != 'whale');
var nam = 'Aleez';
console.log(nam == 'aleez');
var num = 4;
console.log(num > 2);
console.log(num == 3 || num == 4);
var num12 = 3;
console.log(num12 == 2 && num12 == 2);
var arr = ['apple', 'mango'];
console.log(arr.indexOf('mango') !== -1);
